name: COMET Seniors

on:
  schedule:
    - cron: "0 1 1 JAN *"
  workflow_dispatch:

jobs:
  call-comet:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Update - COMET API Seniors
      SENIORS_API_CALL: ${{ secrets.SENIORS_API_CALL }}

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Install npm deps
        working-directory: ./callcomet
        run: npm ci

      - name: Call API - seniors info
        working-directory: ./callcomet
        run: node seniors.js

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ env.CI_COMMIT_MESSAGE }}